{% set versions = {
    "4.1.3": "10fe6d5a3c09b78f8b8aaf550c118a6f8b63f7300224032b233e66b95a0592e0"
} %}


{% set version = environ.get('COMMIT_VERSION', None) %}
{% set version = version or versions.keys()|first %}
{% set version = version|string %}

package:
  name: {{ environ.get('ANACONDA_PACKAGE', "nlojet++")|string|lower }}
  version: {{ environ.get('ANACONDA_VERSION', version)|replace("-", ".") }}

source:
  url: "http://desy.de/~znagy/hep-programs/nlojet++/nlojet++-{{ version }}.tar.gz"
  {% if versions.get(version, None) %}
  sha256: {{ versions.get(version) }}
  {% endif %}

requirements:
  build:
    - {{ compiler('gfortran') }}
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}

    - make

about:
  home: "https://www.desy.de/~znagy/Site/NLOJet++.html"
  license: "GPL-3.0"
  summary: "NLOJET++ is a C++ program for calculating LO and NLO order cross section."

extra:
  recipe-maintainers:
    - meiyasan
